// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD--UvLsUVZKqyVthYd8ygYrOjyA2zSvaI',
    appId: '1:233811186098:web:227957ff9dcf0602eed4ab',
    messagingSenderId: '233811186098',
    projectId: 'my-secretary-e7c8b',
    authDomain: 'my-secretary-e7c8b.firebaseapp.com',
    storageBucket: 'my-secretary-e7c8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrW3e5DvHcv6Z590J6CHK2fCIVD32R-hc',
    appId: '1:233811186098:android:35c09ae32e41cf69eed4ab',
    messagingSenderId: '233811186098',
    projectId: 'my-secretary-e7c8b',
    storageBucket: 'my-secretary-e7c8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAotHqUenYpBJCvu8vZ1MwE_6QTube86Hs',
    appId: '1:233811186098:ios:5f8b1cb9371f5ff0eed4ab',
    messagingSenderId: '233811186098',
    projectId: 'my-secretary-e7c8b',
    storageBucket: 'my-secretary-e7c8b.appspot.com',
    iosBundleId: 'com.example.mySecretary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAotHqUenYpBJCvu8vZ1MwE_6QTube86Hs',
    appId: '1:233811186098:ios:5f8b1cb9371f5ff0eed4ab',
    messagingSenderId: '233811186098',
    projectId: 'my-secretary-e7c8b',
    storageBucket: 'my-secretary-e7c8b.appspot.com',
    iosBundleId: 'com.example.mySecretary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD--UvLsUVZKqyVthYd8ygYrOjyA2zSvaI',
    appId: '1:233811186098:web:f9ca104578d7b26aeed4ab',
    messagingSenderId: '233811186098',
    projectId: 'my-secretary-e7c8b',
    authDomain: 'my-secretary-e7c8b.firebaseapp.com',
    storageBucket: 'my-secretary-e7c8b.appspot.com',
  );
}
